version: '3.8'

services:
  drone-backend:
    build: .
    container_name: surveillance-drone-backend
    ports:
      - "5000:5000"
      - "5001:5001"
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
      - ./dronecore/config:/app/dronecore/config
    environment:
      - ENVIRONMENT=production
      - DATABASE_URL=sqlite:///data/drone_data.db
      - LOG_LEVEL=INFO
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"  # MAVLink
      - "/dev/ttyACM0:/dev/ttyACM0"  # GPS
      - "/dev/video0:/dev/video0"    # Camera
    privileged: true
    restart: unless-stopped
    depends_on:
      - redis

  drone-dashboard:
    build: ./dashboard
    container_name: surveillance-drone-dashboard
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
      - REACT_APP_SOCKET_URL=http://localhost:5001
    depends_on:
      - drone-backend
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: surveillance-drone-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: surveillance-drone-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - drone-backend
      - drone-dashboard
    restart: unless-stopped

volumes:
  redis_data:
