camera:
  device_id: 0
  resolution:
    width: 1920
    height: 1080
  fps: 30
  quality: "high"
  auto_exposure: true
  auto_white_balance: true

streaming:
  enabled: true
  format: "mjpeg"
  quality: 85
  bitrate: 2500000

recording:
  enabled: true
  format: "mp4"
  codec: "h264"
  path: "data/recordings/"
